#!bin/bash/

index=$( cat ko-list-prep.txt )

array=(
$index
)

echo "" > kegg-clustering.txt

for i in "${array[@]}" ; do

        ii=$(awk -F '|' '{print $2}' <<< ${i} )
        #path=$( lynx -dump https://www.genome.jp/entry/${ii} | head -n 250 | sed -n '/Pathway/,/Module/p' | head -n -1 )
        api1=$( lynx -dump https://rest.kegg.jp/link/pathway/${ii} | head -n 1 | awk -F ':' '{print $3}' )
        api2=$( lynx -dump "https://rest.kegg.jp/find/pathway/${api1}" | head -n 1 )
        rxn1=$( lynx -dump "https://rest.kegg.jp/link/reaction/${ii}" | head -n 1 | awk -F ':' '{print $3}' )
        rxn2="$( lynx -dump "https://rest.kegg.jp/find/reaction/${rxn1}" | head -n 1 )"
        #q="$(sed 's/\=//g' <<< $rxn2 )"
        echo "${i} | ${ii} | ${api2} | ${rxn2}"
        echo "${i} | ${ii} | ${api2} | ${q}" >> kegg-clustering.txt

done
